name: Multipass PoC
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1

    - name: Install LXD
      uses: whywaita/setup-lxd@v1

    - run: |
          sudo apt-get update # is it necessary?
          sudo apt-get install --reinstall resolvconf
          
          sudo snap install multipass
          
          echo -e "\nps =>"
          ps -elf | grep multipass
          
          echo -e "\n/var/snap/multipass/ =>"
          ls -l /var/snap/multipass/
          
          echo -e "\n/var/snap/multipass/common =>"
          ls -l /var/snap/multipass/common
          
          echo -e "\n/var/snap/multipass/common/multipass_socket =>"
          ls -l /var/snap/multipass/common/multipass_socket
          
          echo -e "\nsyslog =>"
          cat /var/log/syslog|grep multipass

          echo -e "\nlaunch =>"
          sudo multipass launch impish