name: Multipass PoC
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          sudo snap install multipass
          
          echo "ps"
          ps -elf | grep multipass
          
          echo "/var/snap/multipass/ =>"
          ls -l /var/snap/multipass/
          
          echo "/var/snap/multipass/common =>"
          ls -l /var/snap/multipass/common
          
          echo "/var/snap/multipass/common/multipass_socket =>"
          ls -l /var/snap/multipass/common/multipass_socket
          
          echo "launch"
          sudo multipass launch impish